version: '3'

services:
  datanode:
    #    image:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - driver:/dfs
    ports:
      - 7777:7777
volumes:
  driver:
